"""update project

Revision ID: 60c57cd33b1a
Revises: 42bd1ec2367d
Create Date: 2023-01-19 04:27:52.663285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c57cd33b1a'
down_revision = '42bd1ec2367d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=250), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('project_start', sa.Date(), nullable=False),
    sa.Column('project_end', sa.Date(), nullable=False),
    sa.Column('project_status', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
